{-

https://projecteuler.net/problem=2

	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

-}

fib n = if n < 3 then 1 else fib (n-1) + fib (n-2)
fibs = map fib [1..]

small_fibs max = takeWhile (\f -> f < max) fibs
answer max = sum [ f | f <- small_fibs max, mod f 2 == 0 ]

{-

*Main> answer 4000000
4613732

but this is extremely slow.

-}
